version: "3.8"

services:
  nao_drawing_board_dev:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    command: npm run dev
